/**
 * @interview/shared-types
 *
 * All types shared across packages. Rules:
 *   - No runtime code — types and interfaces only
 *   - Date fields in DB-persisted types use `Date | string` so
 *     they round-trip correctly through JSONB (stored as ISO string,
 *     read back as string, re-hydrated by the caller if needed)
 */

// ============================================================
// CORE IDENTITY
// ============================================================

export type UserId = string;      // Our internal UUID — PK for the entire system
export type ClerkUserId = string; // Clerk's ID — stored but NEVER used as FK
export type SessionId = string;
export type InterviewId = string;

// ============================================================
// USER
// ============================================================

export interface User {
  id: UserId;
  clerkUserId: ClerkUserId;
  email: string;
  fullName: string | null;
  avatarUrl: string | null;
  createdAt: Date | string;
  updatedAt: Date | string;
}

// ============================================================
// INTERVIEW SESSION
// ============================================================

export type InterviewType    = "system_design" | "behavioral" | "domain_knowledge";
export type InterviewTier    = "T1" | "T2" | "T3";
export type InterviewLevel   = "junior" | "mid" | "senior" | "staff" | "principal";
export type HireSignal       = "strong_hire" | "hire" | "no_hire" | "strong_no_hire";
export type SessionStatus    =
  | "initializing" | "ready" | "active"
  | "paused" | "completed" | "abandoned";

export interface SessionMetadata {
  durationSeconds: number;
  totalExchanges: number;
  silenceEvents: number;
  probeCount: number;
  redirectCount: number;
}

export interface InterviewSession {
  id: InterviewId;
  userId: UserId;
  type: InterviewType;
  tier: InterviewTier;
  level: InterviewLevel;
  role: string;
  jdText: string | null;
  resumeText: string | null;
  status: SessionStatus;
  currentPhase: number;
  hireSignal: HireSignal | null;
  overallScore: number | null;
  report: InterviewReport | null;
  metadata: SessionMetadata;
  createdAt: Date | string;
  updatedAt: Date | string;
  completedAt: Date | string | null;
}

// ============================================================
// TRANSCRIPT
// ============================================================

export type MessageRole = "interviewer" | "candidate" | "system";
export type MessageType =
  | "question" | "answer" | "follow_up" | "probe"
  | "redirect" | "nudge" | "clarification" | "summary" | "system_event";

export interface MessageMetadata {
  silenceDurationMs?: number;
  probeIndex?: number;
  flags?: string[];
  timerMs?: number;
  [key: string]: unknown; // extensible for per-phase metadata
}

export interface TranscriptMessage {
  id: string;
  sessionId: InterviewId;
  sequenceIndex: number;
  role: MessageRole;
  type: MessageType;
  content: string;
  phase: number;
  stateName: string;
  metadata: MessageMetadata;
  createdAt: Date | string;
}

// ============================================================
// INTERVIEW PLAN — generated by the AI planner pre-session
// ============================================================

export interface RubricDimension {
  name: string;
  weight: number;  // 0.0–1.0; all weights in a rubric must sum to 1.0
  description: string;
  scoreDescriptors: {
    "0": string;
    "0.5": string;
    "1": string;
  };
}

export interface PlannedQuestion {
  id: string;
  phase: number;
  content: string;
  rubric: RubricDimension[];
  probes: string[];
  tradeoffs?: string[];
  estimationTargets?: string[];
  followUps?: string[];
  expectedScope?: string;
  starLRequired?: boolean;
}

export interface InterviewPlan {
  type: InterviewType;
  questions: PlannedQuestion[];
  competencies?: string[];
  domains?: string[];
  estimationTargets?: string[];
}

/**
 * Represents the candidate's response content.
 * Used in state machine events.
 */
export type CandidateResponse = string;
// ============================================================
// SCORING
// ============================================================

export interface DimensionScore {
  dimension: string;
  score: number;           // 0.0–1.0
  evidence: string;
  transcriptIndices: number[];
}

export interface ImprovementItem {
  area: string;
  observation: string;
  recommendation: string;
  priority: "high" | "medium" | "low";
}

export interface TranscriptEvidence {
  claim: string;
  transcriptIndex: number;
  quote: string;
  signal: "positive" | "negative" | "neutral";
}

export interface AuthenticityFlag {
  type:
    | "story_overlap"
    | "detail_inconsistency"
    | "low_specificity"
    | "potential_fabrication";
  description: string;
  severity: "soft" | "hard";
  forReviewer: boolean;
}

export interface CrossRoundMetaScore {
  systemDesignScore: number | null;
  behavioralScore: number | null;
  domainKnowledgeScore: number | null;
  /** Minimum across all three rounds — NOT average */
  finalHireSignal: HireSignal;
  /** Stored as ISO string in JSONB; re-hydrate with new Date() if needed */
  computedAt: Date | string;
}

export interface InterviewReport {
  sessionId: InterviewId;
  type: InterviewType;
  hireSignal: HireSignal;
  overallScore: number;
  dimensionScores: DimensionScore[];
  strengthSummary: string;
  improvementPlan: ImprovementItem[];
  transcriptEvidence: TranscriptEvidence[];
  authenticityFlags?: AuthenticityFlag[];
  depthProfile?: "specialist" | "generalist" | "T-shaped";
  coachabilityScore?: number;
  crossRoundMetaScore?: CrossRoundMetaScore;
  /** Stored as ISO string in JSONB; re-hydrate with new Date() if needed */
  generatedAt: Date | string;
}

// ============================================================
// BEHAVIORAL — STAR scoring
// ============================================================

export interface CompetencyPlan {
  competency: string;
  question: string;
  expectedScope: string;
  starLRequired: boolean;
  followUps: string[];
}

export interface StarScore {
  competency: string;
  situation: number;
  task: number;
  action: number;
  result: number;
  learning?: number;  // Senior+ only
  scopeMatch: boolean;
  resultDepthProbed: boolean;
}

export interface AdversityScore {
  accountability: number;
  recoveryArc: number;
  noBlame: boolean;
  learningQuality: number;
  noHireSignal: boolean;
  verbatimEvidence?: string;
}

export interface InfluenceScore {
  scopeLevel: 1 | 2 | 3 | 4;
  stakeholderSpecificity: number;
  frictionHandled: boolean;
  businessOutcome: boolean;
}

// ============================================================
// DOMAIN KNOWLEDGE
// ============================================================

export interface DomainPlan {
  domain: string;
  resumeEvidenceLevel: "weak" | "medium" | "strong";
  jdWeight: number;
  questions: {
    conceptual: string;
    applied: string;
    edgeCase: string;
  };
}

export interface ClaimValidation {
  claim: string;
  source: "resume" | "interview";
  validated: boolean;
  depth: "tutorial" | "production" | "expert";
  inflationFlag: boolean;
}

// ============================================================
// STATE MACHINE — context snapshots stored in JSONB
// These are the denormalized shapes stored in interview_sessions
// (separate from the full XState machine context types in state-machines package)
// ============================================================

export interface ProbeRecord {
  phase: number;
  probeIndex: number;
  response: "acknowledged_explained" | "defensive" | "partial" | null;
  score: number;
}

export interface SystemDesignContext {
  problemNavPenalty: boolean;
  reqCoverageScore: number;
  weakNfrFlag: boolean;
  estimationScore: number;
  componentCoverage: number;
  tradeoffScore: number;
  collaborationSignal: "adapted_well" | "defended_ok" | "became_defensive" | null;
  negativeCollabFlag: boolean;
  selfAwarenessScore: 0 | 0.5 | 1;
  probeHistory: ProbeRecord[];
}

export interface BehavioralContext {
  competencyPlan: CompetencyPlan[];
  levelFlag: InterviewLevel;
  followUpIntensity: "hard" | "medium" | "scaffolded";
  attributionFlag: boolean;
  starScores: StarScore[];
  adversityScore: AdversityScore | null;
  influenceScore: InfluenceScore | null;
  authenticityFlags: AuthenticityFlag[];
}

export interface DomainKnowledgeContext {
  domainPlan: DomainPlan[];
  overconfidenceFlag: boolean;
  claimValidationMap: ClaimValidation[];
  productionDepthScores: number[];
  coachabilityScore: number;
  depthProfile: "specialist" | "generalist" | "T-shaped" | null;
}

// ============================================================
// API CONTRACTS
// ============================================================

export interface ApiResponse<T> {
  data: T | null;
  error: ApiError | null;
  meta?: Record<string, unknown>;
}

export interface ApiError {
  code: string;
  message: string;
  details?: Record<string, unknown>;
}

export interface PaginatedResponse<T> {
  data: T[];
  total: number;
  page: number;
  pageSize: number;
  hasMore: boolean;
}

// ============================================================
// WEBSOCKET PROTOCOL
// ============================================================

export type WsMessageType =
  | "session_state_update"
  | "interviewer_message"
  | "phase_transition"
  | "session_complete"
  | "error"
  | "ping"
  | "pong";

export interface WsMessage<T = unknown> {
  type: WsMessageType;
  sessionId: SessionId;
  payload: T;
  timestamp: string;  // ISO 8601
}

export interface WsStateUpdate {
  phase: number;
  stateName: string;
  isComplete: boolean;
}

export interface WsInterviewerMessage {
  content: string;
  isNudge?: boolean;
  stateUpdate?: WsStateUpdate;
}
